name: flutter_polls
description: Customizable Polls for Flutter.
version: 0.0.1
homepage: https://github.com/thenifemi/flutter_polls

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  percent_indicator: ^4.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
